#!/bin/bash

set -e

if [ -z "$ANDROID_NDK" ]; then
   echo "export the ANDROID_NDK environment variable"
   exit 1
fi

# Only choose one of these, depending on your build machine...
export TOOLCHAIN=$ANDROID_NDK/toolchains/llvm/prebuilt/darwin-x86_64
#export TOOLCHAIN=$ANDROID_NDK/toolchains/llvm/prebuilt/linux-x86_64

# create links to some toolchains binaries (https://github.com/android/ndk/issues/1324)
cd $TOOLCHAIN/bin/
for source in arm-linux-androideabi-*
do
    dest=${source/arm/armv7a}
    ln -sf $source $dest
done
cd -

# Set this to your minSdkVersion.
export API=21

pwd=`pwd`

buildit()
{
    abi=$1
    target=$2

    echo ""
    echo "-------------------------------------------------------------------------------"
    echo " Compiling for $abi"
    echo "-------------------------------------------------------------------------------"

    export TARGET=$target

    # Configure and build.
    export AR=$TOOLCHAIN/bin/$TARGET-ar
    export AS=$TOOLCHAIN/bin/$TARGET-as
    export CC=$TOOLCHAIN/bin/$TARGET$API-clang
    export CXX=$TOOLCHAIN/bin/$TARGET$API-clang++
    export LD=$TOOLCHAIN/bin/$TARGET-ld
    export RANLIB=$TOOLCHAIN/bin/$TARGET-ranlib
    export STRIP=$TOOLCHAIN/bin/$TARGET-strip

    ./configure --prefix="$pwd/android/$abi" --host=$TARGET --disable-benchmark

    make clean
    make
    make install
}


buildit armeabi-v7a armv7a-linux-androideabi
buildit arm64-v8a   aarch64-linux-android
buildit x86         i686-linux-android
buildit x86_64      x86_64-linux-android

make clean

echo "done. the files are in the android folder"
